---
- hosts: all
  become: yes
  tasks:

    - name: add group consul
      group: name='consul'

    - name: add consul user
      user: name='consul' groups="consul"

    - name: add hashicorp key 
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present

    - name: add hashicorp repo 
      apt_repository:
        repo: deb https://apt.releases.hashicorp.com focal main
        state: present

    - name: ensure apt cache is updated
      action: apt update_cache=yes

    - name: ensure all software is installed
      action: apt name={{item}}
      with_items:
        - consul
        - nomad
        - vault

    - name: Creates config dir
      file:
        path: /etc/consul.d
        state: directory
        owner: consul
        group: consul
        mode: 0755
    - name: Creates certs dir
      file:
        path: /etc/consul.d/certs
        state: directory
        owner: consul
        group: consul
        mode: 0755

    - name: Creates data dir
      file:
        path: /opt/consul
        state: directory
        owner: consul
        group: consul
        mode: 0755

    - name: copy service file
      copy:
        src: consul.service
        dest: /etc/systemd/system/consul.service

- hosts: consul_servers
  become: yes

  tasks:
    - name: copy agent ca 
      copy:
        src: secrets/consul-agent-ca.pem
        dest: /etc/consul.d/certs/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0644
    - name: copy server pem
      copy:
        src: secrets/dc1-server-consul-0.pem
        dest: /etc/consul.d/certs/dc1-server-consul-0.pem
        owner: consul
        group: consul
        mode: 0644

    - name: copy server key
      copy:
        src: secrets/dc1-server-consul-0-key.pem
        dest: /etc/consul.d/certs/dc1-server-consul-0-key.pem
        owner: consul
        group: consul
        mode: 0644
    - name: copy server config
      copy:
        src: secrets/consul-server.hcl
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: 0644
    - name: Restart consul service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: consul

- hosts: consul_agents
  become: yes

  tasks:
    - name: copy agent ca 
      copy:
        src: secrets/consul-agent-ca.pem
        dest: /etc/consul.d/certs/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0644
    - name: copy agent config
      copy:
        src: secrets/consul-agent.hcl
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: 0644
    - name: Restart consul service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: consul